services:
    sasf.ajaxpreview.controller.preview:
        class: sasf\ajaxpreview\controller\preview
        arguments:
            - '@request'
            - '@user'
            - '@auth'
            - '@config'
    
    sasf.ajaxpreview.listener:
        class: sasf\ajaxpreview\event\listener
        arguments:
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.subscriber } 